theme: jekyll-theme-slate
title: Mandala Workshops
description: Workshop instructions and materials for Mandala, a content management system created by SHANTI and the Contemplative Sciences Center at the University of Virginia.
